name: Deploy Infrastructure

on:
  workflow_dispatch

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Terraform Init
      uses: hashicorp/setup-terraform@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: '02-CICD-infra-gcp/terraform'
        PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID_A}}
        APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

    - name: Terraform Validate
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Apply
      uses: hashicorp/setup-terraform@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: '02-CICD-infra-gcp/terraform'
        PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID_A}}
        APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}